### ISSUE TITLE
JavaScript error when clicking the button

### ISSUE THREAD

**Issue by Shelob9** [8bitgentleman/roam-depot-tweet-extract#1]
I activated this extension in roam. Whenever I load a page in Chrome (I am using Windows 10 Pro, Chrome Version 103.0.5060.134), I see this message in the console:

```
kwift.CHROME.js:3 [Report Only] Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

When I click the button next to a tweet, I get this error:
```
widgets.js:1 Uncaught (in promise) Error: No target element specified. Expected: ƒ(tweetId, target, [options]);
    at Object.<anonymous> (widgets.js:1:13407)
    at Object.a (widgets.js:8:64530)
    at main.js:3729:245
```

**Comment by 8bitgentleman** [comment]
Couple things:

1. What button are you pressing next to the tweet? This plugin does not add any buttons to tweets. Can you include a screenshot?
2. The widget.js error happens to me as well in vanilla roam without this extension installed. Seems to be an internal Roam error.
3.  I do not know what `kwift.CHROME.js` is but it is not included

**Comment by 8bitgentleman** [comment]
Closing this since there was no response and it does not seem related to the extension
