### ISSUE TITLE
Feature suggestion: save the twitter picture in roam.

### ISSUE THREAD

**Issue by fansanqiu** [8bitgentleman/roam-depot-tweet-extract#4]
How about adding the picture on twitter in roam?

I want to save the image without being deleted, It will be very helpful for me~

**Comment by 8bitgentleman** [comment]
I implemented this and then Twitter changed their API making picture extraction unfeasible for now :/ If/when the API stabilizes I will add it back in

**Comment by fansanqiu** [comment]
Thanks.
