### ISSUE TITLE
Glitch hosting

### ISSUE THREAD

**Issue by cori** [8bitgentleman/roam-depot-tweet-extract#6]
Hey there, I saw you moved this to Glitch, perhaps after seeing me do so on https://github.com/mbrock/telegroam/pull/31. 

We've made a change that is going to make these projects unhostable on Glitch for the time being - I'm going to look for a solution that will still be Glitch-hostable. 

Apologies for the inconvenience!

**Comment by 8bitgentleman** [comment]
Yeah I did move after you blazed the trail over on telegram.  Just saw there was some issues with my glitch hosting. I'm curious, what changed?

**Comment by cori** [comment]
Hello! We made an overbroad change to some automated processes, but we discussed this today and agreed on an alternative - i believe you also heard from Support about it - your project should be all set again!

Sorry for the bother!
