### ISSUE TITLE
doesn't work on Roam Research

### ISSUE THREAD

**Issue by machidakei** [8bitgentleman/roam-depot-tweet-extract#7]
Thank you always for supporting us.

Today I have tried to extract a tweet, but it falied.
like this:
<img width="867" alt="CleanShot 2023-04-06 at 12 25 05@2x" src="https://user-images.githubusercontent.com/16206618/230264619-a1cca272-8ff1-4eca-8b4e-1f4677679639.png">

I did that on:
tweet URL:
https://twitter.com/elonmusk/status/1644095821753856002?s=61&t=cpa98IqIn3-5XfzXDIZjkA
https://twitter.com/yoshikawanori/status/1487223810780971008?s=61&t=4oxPZ0rOgI6uxWbQ2kRMRA
Mac OS 13.2.1
ROAM VERSION:
0.9.9-ad29f752

**Comment by genki3ng** [comment]
same here, guess it is caused by the Twitter API policy change?

**Comment by 8bitgentleman** [comment]
Yes, this is due to the recent twitter API change. I have a fix/workaround waiting for approval by the Roam Team to get this working again (without tweet image extraction unfortunately)

**Comment by 8bitgentleman** [comment]
The fix is available in Roam Depot now, if the twitter API is stable image extraction is used if not images are skipped
